initial_position:
  left_upper_arm_y_joint: 0.1  # Slightly offset to avoid collision
  left_upper_arm_x_joint: 0.2
  left_forearm_z_joint: 0.1
  left_forearm_x_joint: 0.1
  left_finger_joint: 0.2
  right_upper_arm_y_joint: -0.1
  right_upper_arm_x_joint: -0.2
  right_forearm_z_joint: -0.1
  right_forearm_x_joint: -0.1
  right_finger_joint: 0.2
