cartesian_limits:
  max_trans_vel: 1.0       # Maximum translational velocity (m/s)
  max_trans_acc: 2.25      # Maximum translational acceleration (m/s^2)
  max_trans_dec: -5.0      # Maximum translational deceleration (m/s^2)
  max_rot_vel: 1.57        # Maximum rotational velocity (rad/s)
