controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

left_arm_controller:
  ros__parameters:
    joints:
      - left_upper_arm_y_joint  
      - left_upper_arm_x_joint  
      - left_forearm_z_joint    
      - left_forearm_x_joint 
      - left_finger_joint   
         
    command_interfaces:
      - position
    state_interfaces:
      - position
 
    gains:
      left_upper_arm_y_joint: {p: 10.0, d: 0.1, i: 0.01}
      left_upper_arm_x_joint: {p: 10.0, d: 0.1, i: 0.01}
      left_forearm_z_joint: {p: 10.0, d: 0.1, i: 0.01}
      left_forearm_x_joint: {p: 10.0, d: 0.1, i: 0.01}
      left_finger_joint: {p: 10.0, d: 0.1, i: 0.01}
 
    open_loop_control: true
    allow_integration_in_goal_trajectories: true 

right_arm_controller:
  ros__parameters:
    joints:
      - right_upper_arm_y_joint  
      - right_upper_arm_x_joint 
      - right_forearm_z_joint    
      - right_forearm_x_joint 
      - right_finger_joint   
         
    command_interfaces:
      - position
    state_interfaces:
      - position

    gains:
      right_upper_arm_y_joint: {p: 10.0, d: 0.1, i: 0.01}
      right_upper_arm_x_joint: {p: 10.0, d: 0.1, i: 0.01}
      right_forearm_z_joint: {p: 10.0, d: 0.1, i: 0.01}
      right_forearm_x_joint: {p: 10.0, d: 0.1, i: 0.01}
      right_finger_joint: {p: 10.0, d: 0.1, i: 0.01}

    open_loop_control: true
    allow_integration_in_goal_trajectories: true 
